---
- name: Determine clickhouse-server details
  gather_facts: false
  hosts: all
  vars:
    clickhouse_data_root: "/var/lib/clickhouse/data/graphite"
    clickhouse_store: "/var/lib/clickhouse/store"
    clickhouse_version: "22.6.3.35"
  tasks:
    - name: Execute goss
      ansible.builtin.shell: goss --gossfile /etc/goss/goss.yaml validate --format documentation
      args:
        executable: /bin/bash
      register: goss

    - name: Execute goss (debug output)
      ansible.builtin.debug:
        msg: "{{ goss.stdout }}"

    - name: Check if the Clickhouse store directory exists
      ansible.builtin.stat:
        path: "{{ clickhouse_store }}"
      register: clickhouse_store_dir

    - name: Clickhouse store directory found
      ansible.builtin.fail:
        msg: "Directory {{ clickhouse_store }} not present"
      when: clickhouse_store_dir.stat.isdir is undefined

    - name: Check Clickhouse database health
      ansible.builtin.shell: clickhouse-client --query='select shard_num, replica_num, host_address, slowdowns_count, estimated_recovery_time from system.clusters format Vertical'
      args:
        executable: /bin/bash
      register: health
      failed_when:
        - health.rc == 1

    - name: Check Clickhouse database health (debug output)
      ansible.builtin.debug:
        msg: "{{ health.stdout }}"

    - name: Check for symlinks
      ansible.builtin.stat:
        path: "{{ item }}"
      register: symlink
      become: true
      with_items:
        - "{{ clickhouse_data_root }}/graphite"
        - "{{ clickhouse_data_root }}/graphite_distributed"
        - "{{ clickhouse_data_root }}/graphite_tree"
        - "{{ clickhouse_data_root }}/graphite_tree_distributed"

    - name: Check for symlinks (debug output)
      ansible.builtin.debug:
        msg: "link exists"
      when: symlink.stat.islnk is defined and symlink.stat.islnk

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Show clickhouse-server version
      ansible.builtin.debug:
        msg: "clickhouse-server version: {{ ansible_facts.packages['clickhouse-server'][0]['version'] }}"
      when: "'clickhouse-server' in ansible_facts.packages"

    - name: "Fail if clickhouse-server version is not {{ clickhouse_version }}"
      ansible.builtin.fail:
        msg: "clickhouse-server version: {{ ansible_facts.packages['clickhouse-server'][0]['version'] }}"
      when: ansible_facts.packages['clickhouse-server'][0]['version'] != clickhouse_version
